language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: EXtt3Pu4oOsz/K09uBL5f6iDknJtSsW6GtnXVKkBvUULdItndULzUe8ljPtWqu2ilnqZn36kL5mRuFILRFxLaVmjFx4GxPpPtihLShHOLELoGefnVhbDbv10K+U31YstjzXX9F2NTvywourd5SBjzT3KyRqntYh6p/azTarCvPvcNOK5yDjTG8LzYDC6acZ218VH9JeLY3d7i5KXVd0SqDgeuTqFLOs2PDfe66/8KMNwDQHNbEA+RWhSSesXTzN+n2WWlKnUSs8iN+Emon4OPODxA+AJWU1PbYNJauEORvTHh2vk3nuhkuYWr2xbNJTe2JvyHzfi05yudAotq++m5HutK4kfwBLj4Xx7/y6FhVELBI9Khmz8asVzEwYF2pBwDjy39sQhJDZjCh3qZ27fh8xu5RisyfzeyjCuc1OWUZdZKZIBfWic9eD/bIejcfWpW/DGhc0YY+Yi/zzDE+OuKbjyjVkk/EH2XE6TOJn2waDVbUCymkhtgrNU16GREsejl0oks8MbIaG3SNGD9Qp6EK9EvK+CFu87fuxhRdGAxmLo/o8YiuVByWKUuxSoSjxaJjRx2B6lqT+605p96jLJgJxfLoYJyX7XXtDz1ziuGb4NbM/CcwOUiQXWjhfNTVmm9QLUCvd2E+IlyNouX4/ERnZSQrZTnZQV8ZJ26Fcu3c4=
    # FIREBASE_SECRET
    - secure: OR2Gp635i7arHX0J/tmCYnGyoNZUCYQoz2iOAJRzNqn9YxOlSThQJ67tj7jGBdPJq2ezSk3bwwoDv5QGdLndRNE6VJ/BAcUGsLeqEUrMmTIPXJh2DbvpRvStTz3W7zQzZGCB/OiIzoT+3jDDL80EuZ/m6s0LJmilwkgTfrIpNEnWy495nuKSq9OxTA2IMWK5lZEKEoS2tyvRY8SMstK5lF+vMejXWLN7ChIfP2J5+jMVSSom/Y+4tBvnweIv1URZrQmsRSD2jSlPqIhzbMWePuJt92FeuC+1EP9SzEo+sQrnr3ZsNWL4RNdwq67UEE5jWlkh2EBZD+drIpR1MhzF94BLI1hlh9Ld9p57egoWTTR44xHxga2givkh1aipd0j29X1lByB/ETLrGI3R/XkDlxO1U+BEfsjuXMbWSw+cDCvWyV+lCm6kCzclGxecCZZ1zT6sx3Npt5/OV3UcxC0khiElUXsHyghIdyLqBV+Nz2n4dnwHMH/NH0AbNxFe/FcpqjWqUycpIdAAjlN9SHqdKMI6Bj7SOpjh5co5trCP23BHmwEscG5jTi5vRdGAkEnXDkyVJVbDY/La62l1seNwuHLS4TnQXf0K2aH64nk/oOvWklXIKP5in7B0ADvGloHkXfX0pbLYP8cffDGV1w0xJJ/qO2wTCGDMl7rFPTTJBLY=
